site_name: Jak na WAGO - CODESYS V3.5
nav:
  - 'index.md'
  - 'hardware.md'
  - 'instalace.md'
  - 'projekt.md'
  - 'programovani.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    logo: material/tooltip-question
  language: cs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Přepnout na tmavé zobrazení
      primary: green
      accent: deep-orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Přepnout na světlé zobrazení    
      primary: green
      accent: lime
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.keys
copyright: |
  &copy; 2023 <a href="https://github.com/jaknawago"  target="_blank" rel="noopener">Jak na WAGO</a>